// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/data"
	"backend/internal/job"
	"backend/internal/server"
	"backend/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

func wireApp(confServer *conf.Server, dbCfg *conf.DatabaseConfig, authCfg *conf.AuthConfig, walletCfg *conf.WalletConfig, logger log.Logger) (*kratos.App, *job.SettlementJob, *job.ChainRechargeJob, *job.WinPriceOracleJob, *biz.AdminUsecase, func(), error) {
	dataData, cleanup, err := data.NewData(dbCfg, logger)
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	challengeRepo := data.NewChallengeRepo()
	authUsecase := biz.NewAuthUsecase(userRepo, challengeRepo, authCfg, logger)
	authService := service.NewAuthService(authUsecase)
	walletRepo := data.NewWalletRepo(dataData)
	stakingRepo := data.NewStakingRepo(dataData)
	settingsRepo := data.NewSettingsRepo(dataData)
	walletUsecase := biz.NewWalletUsecase(userRepo, walletRepo, stakingRepo, authCfg, walletCfg, logger)
	walletService := service.NewWalletService(walletUsecase)
	settlementUsecase := biz.NewSettlementUsecase(userRepo, stakingRepo, walletRepo, logger)
	adminUsecase := biz.NewAdminUsecase(userRepo, walletRepo, settingsRepo, settlementUsecase, authCfg, walletCfg, logger)
	adminService := service.NewAdminService(adminUsecase)
	adminLegacyService := service.NewAdminLegacyService(adminUsecase, userRepo, walletRepo, dataData, authCfg, walletCfg)
	settlementJob := job.NewSettlementJob(settlementUsecase, logger)
	chainRechargeJob := job.NewChainRechargeJob(walletRepo, settingsRepo, walletCfg, logger)
	winPriceOracleJob := job.NewWinPriceOracleJob(adminUsecase, walletCfg, logger)
	grpcServer := server.NewGRPCServer(confServer, authService, walletService, logger)
	httpServer := server.NewHTTPServer(confServer, authService, walletService, adminService, adminLegacyService, chainRechargeJob, winPriceOracleJob, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, settlementJob, chainRechargeJob, winPriceOracleJob, adminUsecase, func() {
		cleanup()
	}, nil
}
